name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: rustc --version
    - run: cargo build --all-targets --all-features

  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: rustup component add rustfmt
    - run: cargo fmt --version
    - run: cargo fmt -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: rustup component add clippy
    - run: cargo clippy --version
    - run: cargo clippy --all-targets --features i64
    - run: cargo clippy --all-targets --all-features

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: rustc --version
    - run: cargo test --features i64
    - run: cargo test --features i128
    - run: cargo test --no-default-features --lib --features i64
    - run: cargo test --no-default-features --lib --features i128
    - run: cargo test --no-default-features --lib --features std,i64
    - run: cargo test --no-default-features --lib --features serde,i64
    - run: cargo test --no-default-features --lib --features i64,parity
    - run: cargo test --no-default-features --lib --features i128,parity
    - run: cargo test --all-features

  run-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo run --example usage --features i64

  fuzz:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
        default: true
        components: llvm-tools-preview
    - run: cargo install cargo-fuzz
    - run: cargo fuzz --version
    - run: cargo fuzz run f64 -- -max_total_time=10s
